#!/bin/bash

# simple bash script to get basic system info
# use bash pretty please :)

BLUE='\033[0;34m' 
RED='\033[0;31m'
RESET='\033[0m'

UNAME=$(uname)
if [[ $UNAME = "Linux" ]]; then
  echo -e ${BLUE}Operating System:${RESET} ${UNAME}  
else
  echo -e ${RED}Basicsys currently does not support ${UNAME}.
  exit 1
fi

if [[ -r /etc/os-release ]]; then
  DISTRO=$(cat /etc/os-release | grep PRETTY_NAME | sed -e 's/PRETTY_NAME="//' -e 's/"//')
  echo -e ${BLUE}Linux Distribution:${RESET} $DISTRO
else
  echo -e ${BLUE}Linux Distribution:${RESET} Unknown
fi

WINDOWING=$(export | grep XDG_SESSION_TYPE | sed -e 's/declare -x XDG_SESSION_TYPE="//' -e 's/"//')
echo -e ${BLUE}Session Type:${RESET} ${WINDOWING^}

ARCH=$(uname -m)
echo -e ${BLUE}Architecture:${RESET} $ARCH

DE=$(export | grep XDG_CURRENT_DESKTOP | sed -e 's/declare -x XDG_CURRENT_DESKTOP="//' -e 's/"//')
echo -e ${BLUE}Desktop Environment:${RESET} ${DE^}
